### ISSUE TITLE
Load joint called variants into Hail for each cohort

### ISSUE THREAD

**Issue by JoannaTan** [c-BIG/Hail-AWS-CloudFormation#14]

**Comment by mhebrard** [comment]
I found the jc.qced.vcf on NSCC of: 
* **GUSTO**
* **PRISM**
* **mini**

I transferred the files from `/data/13000026/data/SG10K_Health/xxx/gatk4_hg38.jc.qced.vcf/SG10K_Health_xxx.jc.VQSR-pass-only.split-multiallelic.vcf.gz` to `s3://npmchorus-gnomad/VCF/`

@nicolas-bertin & @justinjj24 if there is other cohort or new jc.vcf ready please let me know.
if there is, please transfer them in a appropriate directory in NSCC and/or create a link into SG10K_Health folder.

Next: I will load the vcf into Hail

**Comment by nicolas-bertin** [comment]
for PRISM I need to update the content of /data/13000026/data/SG10K_Health/PRISM/ 
* its current content corresponds to n=1000 PRISM
* the n=1350 (1000 core + 100 mini + 250 topup) should be  added  and the directory content re-organized

**Comment by mhebrard** [comment]
* GUSTO: 
  * 1,000 individuals
  * 56,941,330 / 58,366,130 variants annotated
  * matrix table: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_GUSTO.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

@nicolas-bertin @Jack-Ow is it ok if I delete GUSTO vcf (without vep) and GUSTO vep_96.site_anno ?

**Comment by mhebrard** [comment]
* SSMP:
  * **vcf**: `s3://npmchorus-gnomad/VCF/SG10K_Health_SSMP.n96.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 10 nodes c5.xlarge
  * **time**: 01:25:10 (loading VCF + VEP + Writing matrix table)
  * **individuals**: 96
  * **variants**: 19,835,683 / 20,250,374 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_SSMP.n96.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
* mini:
  * **vcf**: `s3://npmchorus-gnomad/VCF/SG10K_Health_mini.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 20 nodes c5.xlarge
  * **time**: 04:40:00 (loading VCF + VEP + Writing matrix table)
  * **individuals**: 2014
  * **variants**: 83,716,742 / 86,047,529 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_mini.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
* midi:
  * **vcf**: `s3://npmchorus-gnomad/VCF/SG10K_Health_midi.n4014.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 20 nodes c5.xlarge
  * **time**: 09:19:12
  * **individuals**: 4014
  * **variants**: 118,760,137 / 122,135,593 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_midi.n4014.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
* PRISM:
  * **vcf**: s3://npmchorus-gnomad/VCF/SG10K_Health_PRISM.n1350.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 15 nodes c5.xlarge
  * **time**: 03:47:40
  * **individuals**: 1350
  * **variants**: 58,658,379 / 60,205,563 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_PRISM.n1350.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
* SERI:
  * **vcf**: s3://npmchorus-gnomad/VCF/SG10K_Health_SERI.n1534.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 5 nodes c5.4xlarge
  * **time**: 04:07:55
  * **individuals**: 1,534
  * **variants**: 73,700,553 / 75,712,668 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_SERI.n1534.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
* TTSH:
  * **vcf**: s3://npmchorus-gnomad/VCF/SG10K_Health_TTSH.n957.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 10 nodes c5.4xlarge
  * **time**: 01:15:57
  * **individuals**: 957
  * **variants**: 55,068,494 / 56,308,455 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_TTSH.n957.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by nicolas-bertin** [comment]
for HELIOS (n=2400 joint-called) 
VQSR-computed, VQSR-pass-only, VQSR-pass-only&split_multiallelic) datasets are now available for ingress into Hail/Chorus2

- nscc://data/13000026/shared/13000026_HELIOS/rpd-sg10k-grch38-gatk4-genomicDB-jointcall.n2400/vcf/SG10K_Health_HELIOS.n2400.jc.VQSR.vcf.gz
- nscc://data/13000026/shared/13000026_HELIOS/rpd-sg10k-grch38-gatk4-genomicDB-jointcall.n2400/qced-vcf/SG10K_Health_HELIOS.n2400.jc.VQSR-pass-only.vcf.gz
- nscc://data/13000026/shared/13000026_HELIOS/rpd-sg10k-grch38-gatk4-genomicDB-jointcall.n2400/qced-vcf/SG10K_Health_HELIOS.n2400.jc.VQSR-pass-only.split-multiallelic.vcf.gz

**Comment by mhebrard** [comment]
* MEC:
  * **vcf**: s3://npmchorus-gnomad/VCF/SG10K_Health_MEC.n2986.jc.VQSR-pass-only.split-multiallelic.vcf.gz`
  * **cluster**: 10 nodes c5.4xlarge
  * **time**: 04:20:00
  * **individuals**: 2986
  * **variants**: 94,911,949 / 97,438,293 (annotated/all)
  * **matrix table**: `s3://npmchorus-gnomad/hailoutput/SG10K_Health_MEC.n2986.jc.VQSR-pass-only.split-multiallelic.vep95.vcf.mt`

**Comment by mhebrard** [comment]
I think we can close this thread as we have one hail matrix table for each cohort.
